# Generated by Django 4.1.4 on 2022-12-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mail',
            field=models.EmailField(max_length=20),
        ),
    ]
