# Generated by Django 4.1.4 on 2022-12-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mail',
            field=models.EmailField(max_length=40),
        ),
    ]
