# Generated by Django 4.1.4 on 2022-12-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='carrera',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='lastname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='mail',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
