# Generated by Django 4.1.4 on 2022-12-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_carrera_alter_task_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lastname',
            field=models.CharField(choices=[('Ing de Sistemas', 'Ing de Sistemas'), ('Ing Electrica', 'Ing Electrica'), ('Ing Electronica', 'Ing Electronica'), ('Ing Mecatronica', 'Ing Mecatronica'), ('Ing Industrial', 'Ing Industrial'), ('Ing Civil', 'Ing Civil'), ('Ing Quimica', 'Ing Quimica'), ('Ing de Alimentos', 'Ing de Alimentos'), ('Ing Ambiental', 'Ing Ambiental'), ('Ing en Telecomunicaciones', 'Ing en Telecomunicaciones'), ('Ing Mecanica', 'Ing Mecanica'), ('Arquitectura', 'Arquitectura'), ('Diseño Industrial', 'Diseño Industrial')], default='Ing de Sistemas', max_length=40),
        ),
    ]
