# Generated by Django 4.1.4 on 2022-12-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='task',
            name='lastname',
            field=models.CharField(max_length=40),
        ),
    ]
